### ISSUE TITLE
Does not function on Windows when using PowerShell

### ISSUE THREAD

**Issue by r3Fuze** [bitwes/gut-extension#1]
PowerShell enabled via `"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6\\pwsh.exe"` in `settings.json`
Same problem with all commands, but using `GUT: Show Help` as example.

Running the command will run
`"D:\Steam\steamapps\common\Godot Engine\godot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d -gh`
in the terminal resulting in this error:

```
At line:1 char:73
+ ... amapps\common\Godot Engine\godot.windows.opt.tools.64.exe" -s res://a ...
+                                                                ~~
Unexpected token '-s' in expression or statement.
At line:1 char:76
+ ... ot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d -gh
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'res://addons/gut/gut_cmdln.gd' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnexpectedToken
```

Taking the same command and prepending `.` like this:
`."D:\Steam\steamapps\common\Godot Engine\godot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d -gh`
and running it manually works fine. (Not sure why, I'm new to PowerShell)

Another problem that pops up when fixing this is when running `GUT: Run current script` it adds the `-gselect=test_example.gd` parameter but gives this error from Gut:
```
 ---  Gut  ---
Unrecognized options:  [.gd]
```

Putting the filename in quotes: `-gselect="test_example.gd"` fixes this too.

**Comment by bitwes** [comment]
The code handles `powershell.exe` but does not handle `pwsh.exe`.  Adding that in.
