### ISSUE TITLE
Can't launch extension commands ("command not found")

### ISSUE THREAD

**Issue by conradhappeliv** [bitwes/gut-extension#14]
I believe I've set up this extension correctly: I have Godot Tools installed, I've created the `.gutconfig.json` file, and have set the `godot_tools.editor_path` setting. The extension seems "activated" - the commands are showing up in the command prompt. However, when I try to run _any_ of the 4 provided commands, I get this error (this is for `GUT: Run All`):

![image](https://user-images.githubusercontent.com/4420888/147397284-5e41dce7-36b4-4eaf-a4b4-24cf5242823c.png)

There doesn't seem to be any additional info in the developer console. Any ideas what might be going on?

Versions:
- VSCode 1.63.2
- Windows 10.0.19042
- Godot 3.4
- gut-extension v2.0.0
- godot-tools v1.1.2

**Comment by bitwes** [comment]
* Were you getting this with Godot open for the same project?  
* Are the commands that show up in the prompt run?
* Your tests run fine via command line or though Godot?
* What version of GUT is installed?
* Paste your `.gutconfig.json`.

This kinda sounds similar to the errors I was seeing when I updated the symbols for 3.4.  The errors VSCode gives for extensions are very vague and difficult to debug.

**Comment by conradhappeliv** [comment]
- Yep, Godot is open (the rest of godot-tools seems to be working fine)
- No, the commands aren't being run as far as I can tell.
- Yes, the tests run fine both via the CLI and via the Godot UI. I'm mostly using this command right now: `godot -d -s --no-window addons/gut/gut_cmdln.gd`.
- The latest version from the asset lib (v7.2.0 it looks like).
- I'm mostly using the default `.gutconfig.json` from this repo:
```
{
    "dirs":[
        "res://test/"
    ],
    "include_subdirs":true,
    "ignore_pause":true,
    "log_level":2,
    "should_exit":true,
    "should_maximize":true
}
```

I haven't developed any extensions for VSCode before, but it sure seems like it's being held up before ever reaching anything Godot-related. I can't see any indication that anything Godot-related is being run when launching the commands.

**Comment by bitwes** [comment]
Do you happen to have `addons/gut` in your .gitignore?

I was finally able to reproduce the issue on a windows box.  I first tried the GUT project and was able to run tests.  I then tried running the tests for my game and I got the error.  Every time I would click on a test script I would see an error in the GodotTools terminal:  `Could not load source code from file 'file:.....'`.  I did not get this error when opening the same files in the Godot editor.

That's when I remembered that VSCode loves to ignore files in the .`gitignore`.  I removed `addons/gut` from `.gitingore`, relaunched VSCode and I was able to run tests.

There might be a setting in VSCode to not ignore some or all of the files in the `.gitignore` but I didn't look for it.  Seems like I had worked around the issue in other projects but maybe not.

**Comment by bitwes** [comment]
I knew I had run into this before.  Issue #13 was similar.  I double checked the workaround there and that also fixed it.
.gitignore
```
addons/gut/*
!addons/gut/gut.gd
```

**Comment by conradhappeliv** [comment]
The issue for me is _not_ the `.gitignore` (I saw the other issue and it didn't apply to me). I don't have the addons folder gitignored. Adding `!addons/gut/gut.gd` also doesn't help.

I am also back at my second computer, where, weirdly enough, I've discovered that it works fine there on the exact same code (so same `.gitignore`, `.gutconfig.json`, etc). I don't _feel_ like there's any other environmental differences but there's gotta be something. I also just double checked the versions on my systems - they're all the same as far as I can tell (same VSCode especially, which seems like it would be the obvious culprit).

Any other ideas for what else I can check?

**Comment by bitwes** [comment]
I believe this error only occurs when the Gut plugin is not active.  The only rule for activation is that the workspace contains `**/addons/gut/gut.gd`.  I'm not sure what else could be causing this.

Are you seeing any errors in the GodotTools terminal or the shell window (when launching Godot manually instead of through VSCode)?

There is a test Godot project in this repo.  Try using that project and see if you get the same results.  You have to install GUT since it is not included in the repo.

**Comment by bitwes** [comment]
This seems to be stale, and I changed the way plugin activation works, so this might be fixed.  Please reopen if it doesn't work.
