### ISSUE TITLE
Support Breakpoints and debugger

### ISSUE THREAD

**Issue by bitwes** [bitwes/gut-extension#17]
bitwes/gut#351

There appears to be a way to launch Godot from VSCode and connect the debugger.  It would be great if this could do that as well.

**Comment by bitwes** [comment]
Godot plugin PR created to support debugger arguments.  godotengine/godot-vscode-plugin#362

**Comment by bitwes** [comment]
Awaiting a new release of the godot-vscode-plugin before this can be used.  Will also need to be tested with godot 4.

**Comment by ryanpeach** [comment]
Would love to see this!

**Comment by bitwes** [comment]
Well, we did it!  godot-tools 2.0 came out and I've now added debugger and breakpoint support.  This will be in the next release.
