### ISSUE TITLE
What are the differences betwen .gutconfig.json and .gut_editor_config.json ?

### ISSUE THREAD

**Issue by theludovyc** [bitwes/gut-extension#18]
I discovered gut extension for vscode this morning. I already use gut with editor so I have a .gut_editor_config.json.

I do not understand why I need to create a .gutconfig.json ? Because I just copy/paste my parameters from .gut_editor_config.json in it.

Another question, can I use .gut_editor_config.json instead of .gutconfig.json with vscode extension ?

**Comment by bitwes** [comment]
`.gutconfig.json` is the default config file that GUT looks for when running via the command line.

`.gut_editor_config.json` is used by the in-editor panel (GUT Panel) and is not static.  The panel writes values to it at each run.  Whenever you use the buttons on the GUT Panel to run a script or single test, it writes values for the script, inner class, and test name to the editor config file.  You can use `.gut_editor_config.json` as the start for a `.gutconfig.json` but they should be kept separate.   For example, If you were to run a single test through the editor, then switch to VSCode and try to run any tests then it will still have the test name configured from the run through the editor.

I don't like that users must maintain two configs, but it hasn't bugged me enough yet to add that in yet.

**Comment by theludovyc** [comment]
I see, thank you for you answer :)
