### ISSUE TITLE
Command gut run (all or script) launched with '&' added at beginning

### ISSUE THREAD

**Issue by theludovyc** [bitwes/gut-extension#19]
Hello :),

When I use command Gut: Run all, or Gut: Run Current script, a '&' is added. As you can see
![image](https://user-images.githubusercontent.com/7337158/210577601-5040c337-ab24-44a1-8061-51215110f32f.png)

In case, my path to godot in settings
![image](https://user-images.githubusercontent.com/7337158/210577830-fbfef66f-782f-4eb2-b3c4-dedad6429398.png)

**Comment by bitwes** [comment]
If you remove the `&` does it run?  

Can you try running in another shell as a workaround?  I'm not sure what his going on.  `cmd` and `powershell` should work, though the output isn't as pretty as in `bash`.

**Comment by theludovyc** [comment]
> If you remove the & does it run?

yes

> Can you try running in another shell as a workaround?

Cmd
![image](https://user-images.githubusercontent.com/7337158/210729555-a7a03d2d-2822-40a3-bf11-d212f112b393.png)

Pws
![image](https://user-images.githubusercontent.com/7337158/210729699-c2ce970a-abfc-4174-8c75-75140b7355e4.png)

It is ok to have '&' with Pws.

But I need to change default terminal to Pws, and is not cool.

Plus with powershell we do not see godot still running. And when press ctrl+c is do this ugly thing
![image](https://user-images.githubusercontent.com/7337158/210730697-679d6ec1-ad63-47a4-884f-985df6b55d16.png)

In bash, when press ctrl+c. After you need to type quit to close godot
![image](https://user-images.githubusercontent.com/7337158/210730997-1e9bdb09-ebe6-4707-b5a8-aec67972ec94.png)

**Comment by bitwes** [comment]
The `quit` thing is gross, but it can be ignored if you have GUT setup to start a new terminal session each time (the default configuration).  When setup to start a new terminal, the plugin will end the previous terminal session and start a new one, so you don't have to explicitly end the last session when it hangs.  If you fix the issue and run again then the previous session will be killed.  

This `&` issue will be addressed in the next release.

**Comment by theludovyc** [comment]
I'll get it :)

I used `-gexit` and redo last command by hand.

I did not know GUT close and start new session. I did not really look at it, because at each time I have `&`. I am happy it will addressed in the next release :)

**Comment by bitwes** [comment]
I've looked into this a little more and what I think is happening is that MINGW64 is being run through PowerShell.  This method below determines if PowerShell is being used.  When PowerShell is used the `&` has to be used to run the GUT command.  I'm not sure if there is a way to detect `MINGW64` as the terminal.

``` typescript
    private isShellPowershell(){
        let itIs = false;
        if (process.platform === "win32") {
            const POWERSHELL = "powershell.exe";
            const shell_plugin = vscode.workspace.getConfiguration("terminal.integrated.shell");
            // the default is powershell if not set.
            let shell = (shell_plugin ? shell_plugin.get("windows", POWERSHELL) : POWERSHELL) || POWERSHELL;
            if (shell.endsWith(POWERSHELL) || shell.endsWith('pwsh.exe')) {
                itIs = true;
            }
        }
        return itIs;
    }

    private escapeCommand(cmd: string){
        let cmdEsc = `"${cmd}"`;
        if(this.isShellPowershell()){
            cmdEsc = `&${cmdEsc}`;
        }
        return cmdEsc;
    }
```

**Comment by theludovyc** [comment]
Hello :) !

Thank you to have looked at on this issue. Yes I use MINGW64 on windows so you have certainly right.

Is only powershell use & ?

**Comment by bitwes** [comment]
The next version has a setting for the shell to be used.  This way you can run GUT without having to change your default shell.  Check that out and see if that doesn't help workaround the issue.  Reopen if not.
