### ISSUE TITLE
Provide settings to allow GutExtension to select which terminal to run on

### ISSUE THREAD

**Issue by damjee** [bitwes/gut-extension#28]
When using a non-bash like terminal as default GutExtension can either not work or have issues. IE Powershell, even zsh is laggy sometimes when zsh-autosuggestions is enabled (But these are not GutExtension Issues).

Since vscode extension launches Gut in the default terminal. This forces the user to select a default integrated terminal that best supports GutExtension and not necessarily the terminal they want to use.

Certainly can be worked around but just annoying sometimes.

**Comment by bitwes** [comment]
This is a good idea.

**Comment by bitwes** [comment]
Done, also added an override for the path to godot in case the shell you pick doesn't support the path specified in godot-tools.
