### ISSUE TITLE
Activate extension when Godot project is in a sub-directory

### ISSUE THREAD

**Issue by pcting** [bitwes/gut-extension#6]
I'm in the progress of building out go binding for godot here: [godot-go](https://github.com/godot-go/godot-go). I need support to activate the GUT extension by searching for sub-directories for the `gut.gd` file.

I already have a PR up in the godot-vscode-plugin here: https://github.com/godotengine/godot-vscode-plugin/issues/239

thus, these settings works with both patches:
```
    "gut-extension.additionalOptions": "-d --path test/project",
    "godot_tools.project_path": "test/project"
```
thanks!

**Comment by bitwes** [comment]
This change doesn't require the change to the godot project right?  This is my first and only vscode plugin I've made and wanted to double check before I tried to remember how to test all this stuff again, heh.

**Comment by pcting** [comment]
the change to the godot-vscode-plugin isn't technically required; committing these changes won't break the gut-extension, however, without the changes committed in godot-vscode-plugin, these changes won't be as useful

**Comment by bitwes** [comment]
Tested and merged.  Thanks for the PR.
